// Comprehensive ISO-3166-1 alpha-2 country dataset
export interface CountryDetail {
  name: string;
  prefix: string;
  code: string;
}

export const ALL_COUNTRIES: Record<string, CountryDetail> = {
  AF: { name: "Afghanistan", prefix: "+93", code: "AF" },
  AX: { name: "Åland Islands", prefix: "+358", code: "AX" },
  AL: { name: "Albania", prefix: "+355", code: "AL" },
  DZ: { name: "Algeria", prefix: "+213", code: "DZ" },
  AS: { name: "American Samoa", prefix: "+1-684", code: "AS" },
  AD: { name: "Andorra", prefix: "+376", code: "AD" },
  AO: { name: "Angola", prefix: "+244", code: "AO" },
  AI: { name: "Anguilla", prefix: "+1-264", code: "AI" },
  AQ: { name: "Antarctica", prefix: "+672", code: "AQ" },
  AG: { name: "Antigua & Barbuda", prefix: "+1-268", code: "AG" },
  AR: { name: "Argentina", prefix: "+54", code: "AR" },
  AM: { name: "Armenia", prefix: "+374", code: "AM" },
  AW: { name: "Aruba", prefix: "+297", code: "AW" },
  AC: { name: "Ascension Island", prefix: "+247", code: "AC" },
  AU: { name: "Australia", prefix: "+61", code: "AU" },
  AT: { name: "Austria", prefix: "+43", code: "AT" },
  AZ: { name: "Azerbaijan", prefix: "+994", code: "AZ" },
  BS: { name: "Bahamas", prefix: "+1-242", code: "BS" },
  BH: { name: "Bahrain", prefix: "+973", code: "BH" },
  BD: { name: "Bangladesh", prefix: "+880", code: "BD" },
  BB: { name: "Barbados", prefix: "+1-246", code: "BB" },
  BY: { name: "Belarus", prefix: "+375", code: "BY" },
  BE: { name: "Belgium", prefix: "+32", code: "BE" },
  BZ: { name: "Belize", prefix: "+501", code: "BZ" },
  BJ: { name: "Benin", prefix: "+229", code: "BJ" },
  BM: { name: "Bermuda", prefix: "+1-441", code: "BM" },
  BT: { name: "Bhutan", prefix: "+975", code: "BT" },
  BO: { name: "Bolivia", prefix: "+591", code: "BO" },
  BA: { name: "Bosnia & Herzegovina", prefix: "+387", code: "BA" },
  BW: { name: "Botswana", prefix: "+267", code: "BW" },
  BV: { name: "Bouvet Island", prefix: "+47", code: "BV" },
  BR: { name: "Brazil", prefix: "+55", code: "BR" },
  IO: { name: "British Indian Ocean Territory", prefix: "+246", code: "IO" },
  VG: { name: "British Virgin Islands", prefix: "+1-284", code: "VG" },
  BN: { name: "Brunei", prefix: "+673", code: "BN" },
  BG: { name: "Bulgaria", prefix: "+359", code: "BG" },
  BF: { name: "Burkina Faso", prefix: "+226", code: "BF" },
  BI: { name: "Burundi", prefix: "+257", code: "BI" },
  KH: { name: "Cambodia", prefix: "+855", code: "KH" },
  CM: { name: "Cameroon", prefix: "+237", code: "CM" },
  CA: { name: "Canada", prefix: "+1", code: "CA" },
  IC: { name: "Canary Islands", prefix: "+34", code: "IC" },
  CV: { name: "Cape Verde", prefix: "+238", code: "CV" },
  BQ: { name: "Caribbean Netherlands", prefix: "+599", code: "BQ" },
  KY: { name: "Cayman Islands", prefix: "+1-345", code: "KY" },
  CF: { name: "Central African Republic", prefix: "+236", code: "CF" },
  EA: { name: "Ceuta & Melilla", prefix: "+34", code: "EA" },
  TD: { name: "Chad", prefix: "+235", code: "TD" },
  CL: { name: "Chile", prefix: "+56", code: "CL" },
  CN: { name: "China", prefix: "+86", code: "CN" },
  CX: { name: "Christmas Island", prefix: "+61", code: "CX" },
  CP: { name: "Clipperton Island", prefix: "+33", code: "CP" },
  CC: { name: "Cocos (Keeling) Islands", prefix: "+61", code: "CC" },
  CO: { name: "Colombia", prefix: "+57", code: "CO" },
  KM: { name: "Comoros", prefix: "+269", code: "KM" },
  CG: { name: "Congo - Brazzaville", prefix: "+242", code: "CG" },
  CD: { name: "Congo - Kinshasa", prefix: "+243", code: "CD" },
  CK: { name: "Cook Islands", prefix: "+682", code: "CK" },
  CR: { name: "Costa Rica", prefix: "+506", code: "CR" },
  CI: { name: "Côte d’Ivoire", prefix: "+225", code: "CI" },
  HR: { name: "Croatia", prefix: "+385", code: "HR" },
  CU: { name: "Cuba", prefix: "+53", code: "CU" },
  CW: { name: "Curaçao", prefix: "+599", code: "CW" },
  CY: { name: "Cyprus", prefix: "+357", code: "CY" },
  CZ: { name: "Czechia", prefix: "+420", code: "CZ" },
  DK: { name: "Denmark", prefix: "+45", code: "DK" },
  DG: { name: "Diego Garcia", prefix: "+246", code: "DG" },
  DJ: { name: "Djibouti", prefix: "+253", code: "DJ" },
  DM: { name: "Dominica", prefix: "+1-767", code: "DM" },
  DO: { name: "Dominican Republic", prefix: "+1-809", code: "DO" },
  EC: { name: "Ecuador", prefix: "+593", code: "EC" },
  EG: { name: "Egypt", prefix: "+20", code: "EG" },
  SV: { name: "El Salvador", prefix: "+503", code: "SV" },
  GQ: { name: "Equatorial Guinea", prefix: "+240", code: "GQ" },
  ER: { name: "Eritrea", prefix: "+291", code: "ER" },
  EE: { name: "Estonia", prefix: "+372", code: "EE" },
  ET: { name: "Ethiopia", prefix: "+251", code: "ET" },
  EU: { name: "European Union", prefix: "+388", code: "EU" },
  FK: { name: "Falkland Islands", prefix: "+500", code: "FK" },
  FO: { name: "Faroe Islands", prefix: "+298", code: "FO" },
  FJ: { name: "Fiji", prefix: "+679", code: "FJ" },
  FI: { name: "Finland", prefix: "+358", code: "FI" },
  FR: { name: "France", prefix: "+33", code: "FR" },
  GF: { name: "French Guiana", prefix: "+594", code: "GF" },
  PF: { name: "French Polynesia", prefix: "+689", code: "PF" },
  TF: { name: "French Southern Territories", prefix: "+262", code: "TF" },
  GA: { name: "Gabon", prefix: "+241", code: "GA" },
  GM: { name: "Gambia", prefix: "+220", code: "GM" },
  GE: { name: "Georgia", prefix: "+995", code: "GE" },
  DE: { name: "Germany", prefix: "+49", code: "DE" },
  GH: { name: "Ghana", prefix: "+233", code: "GH" },
  GI: { name: "Gibraltar", prefix: "+350", code: "GI" },
  GR: { name: "Greece", prefix: "+30", code: "GR" },
  GL: { name: "Greenland", prefix: "+299", code: "GL" },
  GD: { name: "Grenada", prefix: "+1-473", code: "GD" },
  GP: { name: "Guadeloupe", prefix: "+590", code: "GP" },
  GU: { name: "Guam", prefix: "+1-671", code: "GU" },
  GT: { name: "Guatemala", prefix: "+502", code: "GT" },
  GG: { name: "Guernsey", prefix: "+44", code: "GG" },
  GN: { name: "Guinea", prefix: "+224", code: "GN" },
  GW: { name: "Guinea-Bissau", prefix: "+245", code: "GW" },
  GY: { name: "Guyana", prefix: "+592", code: "GY" },
  HT: { name: "Haiti", prefix: "+509", code: "HT" },
  HM: { name: "Heard & McDonald Islands", prefix: "+672", code: "HM" },
  HN: { name: "Honduras", prefix: "+504", code: "HN" },
  HK: { name: "Hong Kong", prefix: "+852", code: "HK" },
  HU: { name: "Hungary", prefix: "+36", code: "HU" },
  IS: { name: "Iceland", prefix: "+354", code: "IS" },
  IN: { name: "India", prefix: "+91", code: "IN" },
  ID: { name: "Indonesia", prefix: "+62", code: "ID" },
  IR: { name: "Iran", prefix: "+98", code: "IR" },
  IQ: { name: "Iraq", prefix: "+964", code: "IQ" },
  IE: { name: "Ireland", prefix: "+353", code: "IE" },
  IM: { name: "Isle of Man", prefix: "+44", code: "IM" },
  IL: { name: "Israel", prefix: "+972", code: "IL" },
  IT: { name: "Italy", prefix: "+39", code: "IT" },
  JM: { name: "Jamaica", prefix: "+1-876", code: "JM" },
  JP: { name: "Japan", prefix: "+81", code: "JP" },
  JE: { name: "Jersey", prefix: "+44", code: "JE" },
  JO: { name: "Jordan", prefix: "+962", code: "JO" },
  KZ: { name: "Kazakhstan", prefix: "+7", code: "KZ" },
  KE: { name: "Kenya", prefix: "+254", code: "KE" },
  KI: { name: "Kiribati", prefix: "+686", code: "KI" },
  XK: { name: "Kosovo", prefix: "+383", code: "XK" },
  KW: { name: "Kuwait", prefix: "+965", code: "KW" },
  KG: { name: "Kyrgyzstan", prefix: "+996", code: "KG" },
  LA: { name: "Laos", prefix: "+856", code: "LA" },
  LV: { name: "Latvia", prefix: "+371", code: "LV" },
  LB: { name: "Lebanon", prefix: "+961", code: "LB" },
  LS: { name: "Lesotho", prefix: "+266", code: "LS" },
  LR: { name: "Liberia", prefix: "+231", code: "LR" },
  LY: { name: "Libya", prefix: "+218", code: "LY" },
  LI: { name: "Liechtenstein", prefix: "+423", code: "LI" },
  LT: { name: "Lithuania", prefix: "+370", code: "LT" },
  LU: { name: "Luxembourg", prefix: "+352", code: "LU" },
  MO: { name: "Macao", prefix: "+853", code: "MO" },
  MK: { name: "North Macedonia", prefix: "+389", code: "MK" },
  MG: { name: "Madagascar", prefix: "+261", code: "MG" },
  MW: { name: "Malawi", prefix: "+265", code: "MW" },
  MY: { name: "Malaysia", prefix: "+60", code: "MY" },
  MV: { name: "Maldives", prefix: "+960", code: "MV" },
  ML: { name: "Mali", prefix: "+223", code: "ML" },
  MT: { name: "Malta", prefix: "+356", code: "MT" },
  MH: { name: "Marshall Islands", prefix: "+692", code: "MH" },
  MQ: { name: "Martinique", prefix: "+596", code: "MQ" },
  MR: { name: "Mauritania", prefix: "+222", code: "MR" },
  MU: { name: "Mauritius", prefix: "+230", code: "MU" },
  YT: { name: "Mayotte", prefix: "+262", code: "YT" },
  MX: { name: "Mexico", prefix: "+52", code: "MX" },
  FM: { name: "Micronesia", prefix: "+691", code: "FM" },
  MD: { name: "Moldova", prefix: "+373", code: "MD" },
  MC: { name: "Monaco", prefix: "+377", code: "MC" },
  MN: { name: "Mongolia", prefix: "+976", code: "MN" },
  ME: { name: "Montenegro", prefix: "+382", code: "ME" },
  MS: { name: "Montserrat", prefix: "+1-664", code: "MS" },
  MA: { name: "Morocco", prefix: "+212", code: "MA" },
  MZ: { name: "Mozambique", prefix: "+258", code: "MZ" },
  MM: { name: "Myanmar (Burma)", prefix: "+95", code: "MM" },
  NA: { name: "Namibia", prefix: "+264", code: "NA" },
  NR: { name: "Nauru", prefix: "+674", code: "NR" },
  NP: { name: "Nepal", prefix: "+977", code: "NP" },
  NL: { name: "Netherlands", prefix: "+31", code: "NL" },
  NC: { name: "New Caledonia", prefix: "+687", code: "NC" },
  NZ: { name: "New Zealand", prefix: "+64", code: "NZ" },
  NI: { name: "Nicaragua", prefix: "+505", code: "NI" },
  NE: { name: "Niger", prefix: "+227", code: "NE" },
  NG: { name: "Nigeria", prefix: "+234", code: "NG" },
  NU: { name: "Niue", prefix: "+683", code: "NU" },
  NF: { name: "Norfolk Island", prefix: "+672", code: "NF" },
  MP: { name: "Northern Mariana Islands", prefix: "+1-670", code: "MP" },
  KP: { name: "North Korea", prefix: "+850", code: "KP" },
  NO: { name: "Norway", prefix: "+47", code: "NO" },
  OM: { name: "Oman", prefix: "+968", code: "OM" },
  PK: { name: "Pakistan", prefix: "+92", code: "PK" },
  PW: { name: "Palau", prefix: "+680", code: "PW" },
  PS: { name: "Palestine", prefix: "+970", code: "PS" },
  PA: { name: "Panama", prefix: "+507", code: "PA" },
  PG: { name: "Papua New Guinea", prefix: "+675", code: "PG" },
  PY: { name: "Paraguay", prefix: "+595", code: "PY" },
  PE: { name: "Peru", prefix: "+51", code: "PE" },
  PH: { name: "Philippines", prefix: "+63", code: "PH" },
  PN: { name: "Pitcairn Islands", prefix: "+64", code: "PN" },
  PL: { name: "Poland", prefix: "+48", code: "PL" },
  PT: { name: "Portugal", prefix: "+351", code: "PT" },
  PR: { name: "Puerto Rico", prefix: "+1-787", code: "PR" },
  QA: { name: "Qatar", prefix: "+974", code: "QA" },
  RE: { name: "Réunion", prefix: "+262", code: "RE" },
  RO: { name: "Romania", prefix: "+40", code: "RO" },
  RU: { name: "Russia", prefix: "+7", code: "RU" },
  RW: { name: "Rwanda", prefix: "+250", code: "RW" },
  WS: { name: "Samoa", prefix: "+685", code: "WS" },
  SM: { name: "San Marino", prefix: "+378", code: "SM" },
  ST: { name: "São Tomé & Príncipe", prefix: "+239", code: "ST" },
  SA: { name: "Saudi Arabia", prefix: "+966", code: "SA" },
  SN: { name: "Senegal", prefix: "+221", code: "SN" },
  RS: { name: "Serbia", prefix: "+381", code: "RS" },
  SC: { name: "Seychelles", prefix: "+248", code: "SC" },
  SL: { name: "Sierra Leone", prefix: "+232", code: "SL" },
  SG: { name: "Singapore", prefix: "+65", code: "SG" },
  SX: { name: "Sint Maarten", prefix: "+1-721", code: "SX" },
  SK: { name: "Slovakia", prefix: "+421", code: "SK" },
  SI: { name: "Slovenia", prefix: "+386", code: "SI" },
  SB: { name: "Solomon Islands", prefix: "+677", code: "SB" },
  SO: { name: "Somalia", prefix: "+252", code: "SO" },
  ZA: { name: "South Africa", prefix: "+27", code: "ZA" },
  GS: { name: "South Georgia & South Sandwich Islands", prefix: "+500", code: "GS" },
  KR: { name: "South Korea", prefix: "+82", code: "KR" },
  SS: { name: "South Sudan", prefix: "+211", code: "SS" },
  ES: { name: "Spain", prefix: "+34", code: "ES" },
  LK: { name: "Sri Lanka", prefix: "+94", code: "LK" },
  BL: { name: "St. Barthélemy", prefix: "+590", code: "BL" },
  SH: { name: "St. Helena", prefix: "+290", code: "SH" },
  KN: { name: "St. Kitts & Nevis", prefix: "+1-869", code: "KN" },
  LC: { name: "St. Lucia", prefix: "+1-758", code: "LC" },
  MF: { name: "St. Martin", prefix: "+590", code: "MF" },
  PM: { name: "St. Pierre & Miquelon", prefix: "+508", code: "PM" },
  VC: { name: "St. Vincent & Grenadines", prefix: "+1-784", code: "VC" },
  SD: { name: "Sudan", prefix: "+249", code: "SD" },
  SR: { name: "Suriname", prefix: "+597", code: "SR" },
  SJ: { name: "Svalbard & Jan Mayen", prefix: "+47", code: "SJ" },
  SZ: { name: "Eswatini", prefix: "+268", code: "SZ" },
  SE: { name: "Sweden", prefix: "+46", code: "SE" },
  CH: { name: "Switzerland", prefix: "+41", code: "CH" },
  SY: { name: "Syria", prefix: "+963", code: "SY" },
  TW: { name: "Taiwan", prefix: "+886", code: "TW" },
  TJ: { name: "Tajikistan", prefix: "+992", code: "TJ" },
  TZ: { name: "Tanzania", prefix: "+255", code: "TZ" },
  TH: { name: "Thailand", prefix: "+66", code: "TH" },
  TL: { name: "Timor-Leste", prefix: "+670", code: "TL" },
  TG: { name: "Togo", prefix: "+228", code: "TG" },
  TK: { name: "Tokelau", prefix: "+690", code: "TK" },
  TO: { name: "Tonga", prefix: "+676", code: "TO" },
  TT: { name: "Trinidad & Tobago", prefix: "+1-868", code: "TT" },
  TA: { name: "Tristan da Cunha", prefix: "+290", code: "TA" },
  TN: { name: "Tunisia", prefix: "+216", code: "TN" },
  TR: { name: "Turkey", prefix: "+90", code: "TR" },
  TM: { name: "Turkmenistan", prefix: "+993", code: "TM" },
  TC: { name: "Turks & Caicos Islands", prefix: "+1-649", code: "TC" },
  TV: { name: "Tuvalu", prefix: "+688", code: "TV" },
  UG: { name: "Uganda", prefix: "+256", code: "UG" },
  UA: { name: "Ukraine", prefix: "+380", code: "UA" },
  AE: { name: "United Arab Emirates", prefix: "+971", code: "AE" },
  GB: { name: "United Kingdom", prefix: "+44", code: "GB" },
  US: { name: "United States", prefix: "+1", code: "US" },
  UY: { name: "Uruguay", prefix: "+598", code: "UY" },
  UM: { name: "U.S. Outlying Islands", prefix: "+1", code: "UM" },
  VI: { name: "U.S. Virgin Islands", prefix: "+1-340", code: "VI" },
  UZ: { name: "Uzbekistan", prefix: "+998", code: "UZ" },
  VU: { name: "Vanuatu", prefix: "+678", code: "VU" },
  VA: { name: "Vatican City", prefix: "+39", code: "VA" },
  VE: { name: "Venezuela", prefix: "+58", code: "VE" },
  VN: { name: "Vietnam", prefix: "+84", code: "VN" },
  WF: { name: "Wallis & Futuna", prefix: "+681", code: "WF" },
  EH: { name: "Western Sahara", prefix: "+212", code: "EH" },
  YE: { name: "Yemen", prefix: "+967", code: "YE" },
  ZM: { name: "Zambia", prefix: "+260", code: "ZM" },
  ZW: { name: "Zimbabwe", prefix: "+263", code: "ZW" }
};

// Flags helper mapping to convert country codes to emojis
export const COUNTRY_FLAGS: Record<string, string> = {
  AF: "🇦🇫", AX: "🇦🇽", AL: "🇦🇱", DZ: "🇩🇿", AS: "🇦🇸", AD: "🇦🇩", AO: "🇦🇴", AI: "🇦🇮",
  AQ: "🇦🇶", AG: "🇦🇬", AR: "🇦🇷", AM: "🇦🇲", AW: "🇦🇼", AC: "🇦🇨", AU: "🇦🇺", AT: "🇦🇹",
  AZ: "🇦🇿", BS: "🇧🇸", BH: "🇧🇭", BD: "🇧🇩", BB: "🇧🇧", BY: "🇧🇾", BE: "🇧🇪", BZ: "🇧🇿",
  BJ: "🇧🇯", BM: "🇧🇲", BT: "🇧🇹", BO: "🇧🇴", BA: "🇧🇦", BW: "🇧🇼", BV: "🇧🇻", BR: "🇧🇷",
  IO: "🇮🇴", VG: "🇻🇬", BN: "🇧🇳", BG: "🇧🇬", BF: "🇧🇫", BI: "🇧🇮", KH: "🇰🇭", CM: "🇨🇲",
  CA: "🇨🇦", IC: "🇮🇨", CV: "🇨🇻", BQ: "🇧🇶", KY: "🇰🇾", CF: "🇨🇫", EA: "🇪🇦", TD: "🇹🇩",
  CL: "🇨🇱", CN: "🇨🇳", CX: "🇨🇽", CP: "🇨🇵", CC: "🇨🇨", CO: "🇨🇴", KM: "🇰🇲", CG: "🇨🇬",
  CD: "🇨🇩", CK: "🇨🇰", CR: "🇨🇷", CI: "🇨🇮", HR: "🇭🇷", CU: "🇨🇺", CW: "🇨🇼", CY: "🇨🇾",
  CZ: "🇨🇿", DK: "🇩🇰", DG: "🇩🇬", DJ: "🇩🇯", DM: "🇩🇲", DO: "🇩🇴", EC: "🇪🇨", EG: "🇪🇬",
  SV: "🇸🇻", GQ: "🇬🇶", ER: "🇪🇷", EE: "🇪🇪", ET: "🇪🇹", EU: "🇪🇺", FK: "🇫🇰", FO: "🇫🇴",
  FJ: "🇫🇯", FI: "🇫🇮", FR: "🇫🇷", GF: "🇬🇫", PF: "🇵🇫", TF: "🇹🇫", GA: "🇬🇦", GM: "🇬🇲",
  GE: "🇬🇪", DE: "🇩🇪", GH: "🇬🇭", GI: "🇬🇮", GR: "🇬🇷", GL: "🇬🇱", GD: "🇬🇩", GP: "🇬🇵",
  GU: "🇬🇺", GT: "🇬🇹", GG: "🇬🇬", GN: "🇬🇳", GW: "🇬🇼", GY: "🇬🇾", HT: "🇭🇹", HM: "🇭🇲",
  HN: "🇭🇳", HK: "🇭🇰", HU: "🇭🇺", IS: "🇮🇸", IN: "🇮🇳", ID: "🇮🇩", IR: "🇮🇷", IQ: "🇮🇶",
  IE: "🇮🇪", IM: "🇮🇲", IL: "🇮🇱", IT: "🇮🇹", JM: "🇯🇲", JP: "🇯🇵", JE: "🇯🇪", JO: "🇯🇴",
  KZ: "🇰🇿", KE: "🇰🇪", KI: "🇰🇮", XK: "🇽🇰", KW: "🇰🇼", KG: "🇰🇬", LA: "🇱🇦", LV: "🇱🇻",
  LB: "🇱🇧", LS: "🇱🇸", LR: "🇱🇷", LY: "🇱🇾", LI: "🇱🇮", LT: "🇱🇹", LU: "🇱🇺", MO: "🇲🇴",
  MK: "🇲🇰", MG: "🇲🇬", MW: "🇲🇼", MY: "🇲🇾", MV: "🇲🇻", ML: "🇲🇲", MT: "🇲🇹", MH: "🇲🇭",
  MQ: "🇲🇶", MR: "🇲🇷", MU: "🇲🇺", YT: "🇾🇹", MX: "🇲🇽", FM: "🇫🇲", MD: "🇲🇩", MC: "🇲🇨",
  MN: "🇲🇳", ME: "🇲🇪", MS: "🇲🇸", MA: "🇲🇦", MZ: "🇲🇿", MM: "🇲🇲", NA: "🇳🇦", NR: "🇳🇷",
  NP: "🇳🇵", NL: "🇳🇱", NC: "🇳🇨", NZ: "🇳🇿", NI: "🇳🇮", NE: "🇳🇪", NG: "🇳🇬", NU: "🇳🇺",
  NF: "🇳🇫", MP: "🇲🇵", KP: "🇰🇵", NO: "🇳🇴", OM: "🇴🇲", PK: "🇵🇰", PW: "🇵🇼", PS: "🇵🇸",
  PA: "🇵🇦", PG: "🇵🇬", PY: "🇵🇾", PE: "🇵🇪", PH: "🇵🇭", PN: "🇵🇳", PL: "🇵🇱", PT: "🇵🇹",
  PR: "🇵🇷", QA: "🇶🇦", RE: "🇷🇪", RO: "🇷🇴", RU: "🇷🇺", RW: "🇷🇼", WS: "🇼🇸", SM: "🇸🇲",
  ST: "🇸🇹", SA: "🇸🇦", SN: "🇸🇳", RS: "🇷🇸", SC: "🇸🇨", SL: "🇸🇱", SG: "🇸🇬", SX: "🇸🇽",
  SK: "🇸🇰", SI: "🇸🇮", SB: "🇸🇧", SO: "🇸🇴", ZA: "🇿🇦", GS: "🇬🇸", KR: "🇰🇷", SS: "🇸🇸",
  ES: "🇪🇸", LK: "🇱🇰", BL: "🇧🇱", SH: "🇸🇭", KN: "🇰🇳", LC: "🇱🇨", MF: "🇲🇫", PM: "🇵🇲",
  VC: "🇻🇨", SD: "🇸🇩", SR: "🇸🇺", SJ: "🇸🇯", SZ: "🇸🇿", SE: "🇸🇪", CH: "🇨🇭", SY: "🇸🇾",
  TW: "🇹🇼", TJ: "🇹🇯", TZ: "🇹🇿", TH: "🇹🇭", TL: "🇹🇱", TG: "🇹🇬", TK: "🇹🇰", TO: "🇹🇴",
  TT: "🇹🇹", TA: "🇹🇦", TN: "🇹🇳", TR: "🇹🇷", TM: "🇹🇲", TC: "🇹🇨", TV: "🇹🇺", UG: "🇺🇬",
  UA: "🇺🇦", AE: "🇦🇪", GB: "🇬🇧", US: "🇺🇸", UY: "🇺🇾", UM: "🇺🇲", VI: "🇻🇮", UZ: "🇺🇿",
  VU: "🇻🇺", VA: "🇻🇦", VE: "🇻🇪", VN: "🇻🇳", WF: "🇼🇫", EH: "🇪🇭", YE: "🇾🇪", ZM: "🇿🇲",
  ZW: "🇿🇼"
};
